<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Category::insert(
            [
                // [
                //     'id' => 1,
                //     'name' => 'Root',
                //     'slug' => 'root',

                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 1,
                //     'menu' => 0,
                //     'image' => 'https://via.placeholder.com/640x480.png/00cc88?text=incidunt',
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2023-06-10 04:42:04',
                // ],
                // [
                //     'id' => 11,
                //     'name' => 'Generators',
                //     'slug' => 'generators',
                   
                //     'description' => NULL,
                //     'sorting' => 10,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/kERUc4wpQLlwFvfFXrPE2obvv.Generators.jpg',
                //     'hover_image' => 'categories/bc8mtrS7TZNyZt33nN7Eteur7.Generators.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 1,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2024-06-04 11:37:41',
                // ],
                // [
                //     'id' => 12,
                //     'name' => 'Water Pumps',
                //     'slug' => 'water-pumps',
                   
                //     'description' => NULL,
                //     'sorting' => 6,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/hThQVqaimge46Er10OfO87Nq9.Water-Pumps2.webp',
                //     'hover_image' => 'categories/i5q1T6v8W1C5EBpDa75sm4XNm.water-pump.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 1,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2024-06-03 17:11:49',
                // ],
                // [
                //     'id' => 13,
                //     'name' => 'Air Tools',
                //     'slug' => 'air-tools',
                   
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/lSZVhD1NdmlHKfxXZetnqW2hv.Air-Tools2.webp',
                //     'hover_image' => 'categories/bUDxiqyABWSE6DRre20Nk8nFj.air-Tools.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 1,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2024-06-05 12:30:20',
                // ],
                // [
                //     'id' => 14,
                //     'name' => 'Hand Tools',
                //     'slug' => 'hand-tools',
                   
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/yiW9bgfyNBjHMIEBfw5SOOBn1.Hand-Tools2.webp',
                //     'hover_image' => 'categories/a3oX9uRBxFamHAEhqZKFA4P27.Hand-Tools.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2024-06-05 12:22:42',
                // ],
                // [
                //     'id' => 15,
                //     'name' => 'Industrial Automation Parts & Accessories',
                //     'slug' => 'industrial-automation-parts-accessories',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 6,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => 'categories/3O95AZvHMaTpCruiINtV0LxiU.Accessories2.webp',
                //     'hover_image' => 'categories/B0H9CQJbtVIK4PP6qums1PNAj.Industrial-Automation-Parts-&-Accessories.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-06-10 01:20:49',
                //     'updated_at' => '2024-01-02 15:51:57',
                // ],
                // [
                //     'id' => 16,
                //     'name' => 'Bench Tools',
                //     'slug' => 'bench-tools',
                   
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/XCKpaIziAd23N614jp1OJDBNd.Bench-Tools2.webp',
                //     'hover_image' => 'categories/WRpTU2N075dnk176asUZrEK8f.bench-tools.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-06-14 09:29:16',
                //     'updated_at' => '2024-06-05 13:16:18',
                // ],
                // [
                //     'id' => 18,
                //     'name' => 'Power Tools',
                //     'slug' => 'power-tools',
                   
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/FbbJK14NRu38sAp0x7u3TxJlW.Power-Tools2.webp',
                //     'hover_image' => 'categories/R8ZZvCt8CyV9JWkoOhyMwbsx7.Power-Tools.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-06-25 09:50:09',
                //     'updated_at' => '2024-06-04 17:18:32',
                // ],
                // [
                //     'id' => 20,
                //     'name' => 'Electric Motor',
                //     'slug' => 'electric-motor',
                   
                //     'description' => NULL,
                //     'sorting' => 7,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/cUHv3ikhDRAPw9pU6WvuMeoMS.4.jpg',
                //     'hover_image' => 'categories/E3pPGSmlkgHp8lP3QNUyJhjPr.Electric-Motor.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 1,
                //     'created_at' => '2023-12-19 11:34:41',
                //     'updated_at' => '2024-08-15 13:08:22',
                // ],
                // [
                //     'id' => 21,
                //     'name' => 'Fire Fighting Equipment',
                //     'slug' => 'fire-fighting-equipment',
                   
                //     'description' => NULL,
                //     'sorting' => 8,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/kX4zI8eRI2CyGZFOO50MLgYV6.Fire-Fighting-Equipment.jpg',
                //     'hover_image' => 'categories/TE7c4j1YRMejum9MRTeb0bpsw.Fire-Fighting-Equipment.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 11:36:35',
                //     'updated_at' => '2024-06-04 13:03:43',
                // ],
                // [
                //     'id' => 22,
                //     'name' => 'Safety Products',
                //     'slug' => 'safety-products',
                   
                //     'description' => NULL,
                //     'sorting' => 9,
                //     'featured' => 1,
                //     'menu' => 1,
                //     'image' => 'categories/Rm5Rad2eZMA6erWpmnHGscxU4.Safety-Products.jpg',
                //     'hover_image' => 'categories/qdLXsOOOYIJTSbxZzystbs5BM.Safety-Products.jpg',
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 11:38:29',
                //     'updated_at' => '2024-06-04 13:37:56',
                // ],
                // [
                //     'id' => 23,
                //     'name' => 'Wrenches',
                //     'slug' => 'wrenches',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:28:41',
                //     'updated_at' => '2023-12-19 14:28:41',
                // ],
                // [
                //     'id' => 24,
                //     'name' => 'Pliers',
                //     'slug' => 'pliers',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:29:08',
                //     'updated_at' => '2023-12-19 14:29:42',
                // ],
                // [
                //     'id' => 25,
                //     'name' => 'Spanners',
                //     'slug' => 'spanners',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:29:35',
                //     'updated_at' => '2023-12-19 14:29:35',
                // ],
                // [
                //     'id' => 26,
                //     'name' => 'Screw Drivers',
                //     'slug' => 'screw-drivers',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:30:05',
                //     'updated_at' => '2023-12-19 14:30:05',
                // ],
                // [
                //     'id' => 27,
                //     'name' => 'Cutters',
                //     'slug' => 'cutters',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:30:17',
                //     'updated_at' => '2023-12-19 14:30:17',
                // ],
                // [
                //     'id' => 28,
                //     'name' => 'Bottle Jack & Trolley Jack',
                //     'slug' => 'bottle-jack-trolley-jack',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:30:30',
                //     'updated_at' => '2023-12-19 14:30:30',
                // ],
                // [
                //     'id' => 29,
                //     'name' => 'SAW',
                //     'slug' => 'saw',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:30:41',
                //     'updated_at' => '2023-12-19 14:30:41',
                // ],
                // [
                //     'id' => 30,
                //     'name' => 'Chisel Sets',
                //     'slug' => 'chisel-sets',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:31:06',
                //     'updated_at' => '2023-12-19 14:31:06',
                // ],
                // [
                //     'id' => 31,
                //     'name' => 'AXE',
                //     'slug' => 'axe',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:31:19',
                //     'updated_at' => '2023-12-19 14:31:19',
                // ],
                // [
                //     'id' => 32,
                //     'name' => 'Utility Knife',
                //     'slug' => 'utility-knife',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:31:32',
                //     'updated_at' => '2023-12-19 14:31:32',
                // ],
                // [
                //     'id' => 33,
                //     'name' => 'Ratchet Handle with Socket',
                //     'slug' => 'ratchet-handle-with-socket',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:31:44',
                //     'updated_at' => '2023-12-19 14:31:44',
                // ],
                // [
                //     'id' => 34,
                //     'name' => 'Laser Distance Meter',
                //     'slug' => 'laser-distance-meter',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:31:56',
                //     'updated_at' => '2023-12-19 14:31:56',
                // ],
                // [
                //     'id' => 35,
                //     'name' => 'Clamp Meter',
                //     'slug' => 'clamp-meter',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:32:06',
                //     'updated_at' => '2023-12-19 14:32:06',
                // ],
                // [
                //     'id' => 36,
                //     'name' => 'Hammers',
                //     'slug' => 'hammers',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:32:19',
                //     'updated_at' => '2023-12-19 14:32:19',
                // ],
                // [
                //     'id' => 37,
                //     'name' => 'Hand Tool Sets',
                //     'slug' => 'hand-tool-sets',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:32:32',
                //     'updated_at' => '2023-12-19 14:32:32',
                // ],
                // [
                //     'id' => 38,
                //     'name' => 'Other Tools',
                //     'slug' => 'other-tools',
                //     'parent_id' => 14,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:32:46',
                //     'updated_at' => '2023-12-19 14:32:46',
                // ],
                // [
                //     'id' => 39,
                //     'name' => 'Cordless Drill',
                //     'slug' => 'cordless-drill',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:36:19',
                //     'updated_at' => '2023-12-19 14:36:19',
                // ],
                // [
                //     'id' => 40,
                //     'name' => 'Cordless Screwdriver',
                //     'slug' => 'cordless-screwdriver',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:36:36',
                //     'updated_at' => '2023-12-19 14:36:36',
                // ],
                // [
                //     'id' => 41,
                //     'name' => 'Electric Drill & Impact Drill',
                //     'slug' => 'electric-drill-impact-drill',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:36:49',
                //     'updated_at' => '2023-12-19 14:36:49',
                // ],
                // [
                //     'id' => 42,
                //     'name' => 'Impact Wrench',
                //     'slug' => 'impact-wrench',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:37:10',
                //     'updated_at' => '2023-12-19 14:37:10',
                // ],
                // [
                //     'id' => 43,
                //     'name' => 'Rotary & Demolition Hammer',
                //     'slug' => 'rotary-demolition-hammer',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:37:25',
                //     'updated_at' => '2023-12-19 14:37:25',
                // ],
                // [
                //     'id' => 44,
                //     'name' => 'Angle Grinder',
                //     'slug' => 'angle-grinder',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:37:40',
                //     'updated_at' => '2023-12-19 14:37:40',
                // ],
                // [
                //     'id' => 45,
                //     'name' => 'Electric Saws',
                //     'slug' => 'electric-saws',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:37:55',
                //     'updated_at' => '2023-12-19 14:37:55',
                // ],
                // [
                //     'id' => 46,
                //     'name' => 'Sanders',
                //     'slug' => 'sanders',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:38:08',
                //     'updated_at' => '2023-12-19 14:38:08',
                // ],
                // [
                //     'id' => 47,
                //     'name' => 'Electric Planer & Router',
                //     'slug' => 'electric-planer-router',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:38:22',
                //     'updated_at' => '2023-12-19 14:38:22',
                // ],
                // [
                //     'id' => 48,
                //     'name' => 'Heat Gun & Spray Gun',
                //     'slug' => 'heat-gun-spray-gun',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:38:36',
                //     'updated_at' => '2023-12-19 14:38:36',
                // ],
                // [
                //     'id' => 49,
                //     'name' => 'Blowers',
                //     'slug' => 'blowers',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:38:52',
                //     'updated_at' => '2023-12-19 14:38:52',
                // ],
                // [
                //     'id' => 50,
                //     'name' => 'MMA Welding Machine',
                //     'slug' => 'mma-welding-machine',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 0,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:39:06',
                //     'updated_at' => '2023-12-19 14:39:06',
                // ],
                // [
                //     'id' => 51,
                //     'name' => 'TIG Welding Machine',
                //     'slug' => 'tig-welding-machine',
                //     'parent_id' => 18,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-19 14:39:18',
                //     'updated_at' => '2023-12-21 23:01:01',
                // ],
                // [
                //     'id' => 52,
                //     'name' => 'Bench Grinder',
                //     'slug' => 'bench-grinder',
                //     'parent_id' => 16,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:38:56',
                //     'updated_at' => '2023-12-23 11:38:56',
                // ],
                // [
                //     'id' => 53,
                //     'name' => 'Drill Press',
                //     'slug' => 'drill-press',
                //     'parent_id' => 16,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:39:22',
                //     'updated_at' => '2023-12-23 11:39:22',
                // ],
                // [
                //     'id' => 54,
                //     'name' => 'Cut Off Saw',
                //     'slug' => 'cut-off-saw',
                //     'parent_id' => 16,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:39:52',
                //     'updated_at' => '2023-12-23 11:39:52',
                // ],
                // [
                //     'id' => 55,
                //     'name' => 'Sliding Mitre Saw',
                //     'slug' => 'sliding-mitre-saw',
                //     'parent_id' => 16,
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:40:22',
                //     'updated_at' => '2023-12-23 11:40:22',
                // ],
                // [
                //     'id' => 56,
                //     'name' => 'Piston Type Air Compressor',
                //     'slug' => 'piston-type-air-compressor',
                //     'parent_id' => 13,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:40:56',
                //     'updated_at' => '2023-12-23 11:40:56',
                // ],
                // [
                //     'id' => 57,
                //     'name' => 'Silent Oil Free Air Compressor',
                //     'slug' => 'silent-oil-free-air-compressor',
                //     'parent_id' => 13,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:41:12',
                //     'updated_at' => '2023-12-23 11:41:12',
                // ],
                // [
                //     'id' => 58,
                //     'name' => 'Screw Air Compressor',
                //     'slug' => 'screw-air-compressor',
                //     'parent_id' => 13,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:41:27',
                //     'updated_at' => '2023-12-23 11:41:27',
                // ],
                // [
                //     'id' => 59,
                //     'name' => 'High Pressure Car Washer',
                //     'slug' => 'high-pressure-car-washer',
                //     'parent_id' => 13,
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:41:53',
                //     'updated_at' => '2023-12-23 11:41:53',
                // ],
                // [
                //     'id' => 60,
                //     'name' => 'Vacuum Cleaner',
                //     'slug' => 'vacuum-cleaner',
                //     'parent_id' => 13,
                //     'description' => NULL,
                //     'sorting' => 5,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:42:11',
                //     'updated_at' => '2023-12-23 11:42:11',
                // ],
                // [
                //     'id' => 61,
                //     'name' => 'Diesel Generator',
                //     'slug' => 'diesel-generator',
                //     'parent_id' => 11,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:42:30',
                //     'updated_at' => '2023-12-23 11:42:30',
                // ],
                // [
                //     'id' => 62,
                //     'name' => 'Portable Gasoline Generator',
                //     'slug' => 'portable-gasoline-generator',
                //     'parent_id' => 11,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:42:45',
                //     'updated_at' => '2023-12-23 11:42:45',
                // ],
                // [
                //     'id' => 63,
                //     'name' => 'Borehole Submersible Pump',
                //     'slug' => 'borehole-submersible-pump',
                //     'parent_id' => 12,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:43:03',
                //     'updated_at' => '2023-12-23 11:43:03',
                // ],
                // [
                //     'id' => 64,
                //     'name' => 'Centrifugal Sewage Pump',
                //     'slug' => 'centrifugal-sewage-pump',
                //     'parent_id' => 12,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:43:20',
                //     'updated_at' => '2023-12-23 11:43:20',
                // ],
                // [
                //     'id' => 65,
                //     'name' => 'Vertical Multistage Submersible Pump',
                //     'slug' => 'vertical-multistage-submersible-pump',
                //     'parent_id' => 12,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:43:34',
                //     'updated_at' => '2023-12-23 11:43:34',
                // ],
                // [
                //     'id' => 66,
                //     'name' => 'Jet Water Pump',
                //     'slug' => 'jet-water-pump',
                //     'parent_id' => 12,
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:43:47',
                //     'updated_at' => '2023-12-23 11:43:47',
                // ],
                // [
                //     'id' => 67,
                //     'name' => 'Irrigation Deep Well Pumps',
                //     'slug' => 'irrigation-deep-well-pumps',
                //     'parent_id' => NULL,
                //     'description' => NULL,
                //     'sorting' => 5,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:44:03',
                //     'updated_at' => '2023-12-23 11:44:03',
                // ],
                // [
                //     'id' => 68,
                //     'name' => 'AC Induction Motor',
                //     'slug' => 'ac-induction-motor',
                //     'parent_id' => 20,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:44:26',
                //     'updated_at' => '2023-12-23 11:44:26',
                // ],
                // [
                //     'id' => 69,
                //     'name' => 'Permanent Magnet Electric Motor',
                //     'slug' => 'permanent-magnet-electric-motor',
                //     'parent_id' => 20,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:44:45',
                //     'updated_at' => '2023-12-23 11:44:45',
                // ],
                // [
                //     'id' => 70,
                //     'name' => 'Gear Box',
                //     'slug' => 'gear-box',
                //     'parent_id' => 20,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:45:01',
                //     'updated_at' => '2023-12-23 11:45:01',
                // ],
                // [
                //     'id' => 71,
                //     'name' => 'Fire Extinguishers',
                //     'slug' => 'fire-extinguishers',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:45:22',
                //     'updated_at' => '2023-12-23 11:45:22',
                // ],
                // [
                //     'id' => 72,
                //     'name' => 'Fire Alarm Systems',
                //     'slug' => 'fire-alarm-systems',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:45:35',
                //     'updated_at' => '2023-12-23 11:45:35',
                // ],
                // [
                //     'id' => 73,
                //     'name' => 'Smoke detector',
                //     'slug' => 'smoke-detector',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:45:50',
                //     'updated_at' => '2023-12-23 11:45:50',
                // ],
                // [
                //     'id' => 74,
                //     'name' => 'Heat Detector',
                //     'slug' => 'heat-detector',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:46:07',
                //     'updated_at' => '2023-12-23 11:46:07',
                // ],
                // [
                //     'id' => 75,
                //     'name' => 'Fire Hydrant System',
                //     'slug' => 'fire-hydrant-system',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 5,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:46:26',
                //     'updated_at' => '2023-12-23 11:46:26',
                // ],
                // [
                //     'id' => 76,
                //     'name' => 'Fire Suppression System',
                //     'slug' => 'fire-suppression-system',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 6,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:46:44',
                //     'updated_at' => '2023-12-23 11:46:44',
                // ],
                // [
                //     'id' => 77,
                //     'name' => 'Fire First Aid Kits',
                //     'slug' => 'fire-first-aid-kits',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 7,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:47:08',
                //     'updated_at' => '2023-12-23 11:47:08',
                // ],
                // [
                //     'id' => 78,
                //     'name' => 'Fire Hoses',
                //     'slug' => 'fire-hoses',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 8,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:47:22',
                //     'updated_at' => '2023-12-23 11:47:22',
                // ],
                // [
                //     'id' => 79,
                //     'name' => 'Fire and Welding Blankets',
                //     'slug' => 'fire-and-welding-blankets',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 9,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:47:38',
                //     'updated_at' => '2023-12-23 11:47:38',
                // ],
                // [
                //     'id' => 80,
                //     'name' => 'Sprinklers',
                //     'slug' => 'sprinklers',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 10,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:48:17',
                //     'updated_at' => '2023-12-23 11:48:17',
                // ],
                // [
                //     'id' => 81,
                //     'name' => 'Fire Cabinet',
                //     'slug' => 'fire-cabinet',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 11,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:48:32',
                //     'updated_at' => '2023-12-23 11:48:32',
                // ],
                // [
                //     'id' => 82,
                //     'name' => 'Fire Pump',
                //     'slug' => 'fire-pump',
                //     'parent_id' => 21,
                //     'description' => NULL,
                //     'sorting' => 12,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:48:46',
                //     'updated_at' => '2023-12-23 11:48:46',
                // ],
                // [
                //     'id' => 83,
                //     'name' => 'Industrial gloves',
                //     'slug' => 'industrial-gloves',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 1,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:49:06',
                //     'updated_at' => '2023-12-23 11:49:06',
                // ],
                // [
                //     'id' => 84,
                //     'name' => 'Safety Shoes',
                //     'slug' => 'safety-shoes',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 2,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:49:55',
                //     'updated_at' => '2023-12-23 11:49:55',
                // ],
                // [
                //     'id' => 85,
                //     'name' => 'Industrial Safety Helmet',
                //     'slug' => 'industrial-safety-helmet',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 3,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:50:08',
                //     'updated_at' => '2023-12-23 11:50:08',
                // ],
                // [
                //     'id' => 86,
                //     'name' => 'Safety Googles',
                //     'slug' => 'safety-googles',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 4,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:50:23',
                //     'updated_at' => '2023-12-23 11:50:23',
                // ],
                // [
                //     'id' => 87,
                //     'name' => 'Safety Vest',
                //     'slug' => 'safety-vest',
                //     'parent_id' => 22,
                //     'description' => NULL,
                //     'sorting' => 5,
                //     'featured' => 0,
                //     'menu' => 0,
                //     'image' => NULL,
                //     'hover_image' => NULL,
                //     'status' => 1,
                //     'is_show_top_sidebar' => 0,
                //     'created_at' => '2023-12-23 11:50:37',
                //     'updated_at' => '2023-12-23 11:50:37',
                // ],
            ]
        );
    }
}
