<?php

namespace Database\Seeders;

use App\Models\ProductCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ProductCategory::insert([
            ['id' => 885, 'category_id' => 39, 'product_id' => 3183, 'created_at' => null, 'updated_at' => null],
            ['id' => 886, 'category_id' => 18, 'product_id' => 3183, 'created_at' => null, 'updated_at' => null],
            ['id' => 887, 'category_id' => 39, 'product_id' => 3184, 'created_at' => null, 'updated_at' => null],
            ['id' => 888, 'category_id' => 18, 'product_id' => 3184, 'created_at' => null, 'updated_at' => null],
            ['id' => 889, 'category_id' => 40, 'product_id' => 3185, 'created_at' => null, 'updated_at' => null],
            ['id' => 890, 'category_id' => 18, 'product_id' => 3185, 'created_at' => null, 'updated_at' => null],
            ['id' => 891, 'category_id' => 40, 'product_id' => 3186, 'created_at' => null, 'updated_at' => null],
            ['id' => 892, 'category_id' => 18, 'product_id' => 3186, 'created_at' => null, 'updated_at' => null],
            ['id' => 893, 'category_id' => 39, 'product_id' => 3187, 'created_at' => null, 'updated_at' => null],
            ['id' => 894, 'category_id' => 18, 'product_id' => 3187, 'created_at' => null, 'updated_at' => null],
            ['id' => 895, 'category_id' => 39, 'product_id' => 3188, 'created_at' => null, 'updated_at' => null],
            ['id' => 896, 'category_id' => 18, 'product_id' => 3188, 'created_at' => null, 'updated_at' => null],
            ['id' => 897, 'category_id' => 39, 'product_id' => 3189, 'created_at' => null, 'updated_at' => null],
            ['id' => 898, 'category_id' => 18, 'product_id' => 3189, 'created_at' => null, 'updated_at' => null],
            ['id' => 899, 'category_id' => 39, 'product_id' => 3190, 'created_at' => null, 'updated_at' => null],
            ['id' => 900, 'category_id' => 18, 'product_id' => 3190, 'created_at' => null, 'updated_at' => null],
            ['id' => 901, 'category_id' => 39, 'product_id' => 3191, 'created_at' => null, 'updated_at' => null],
            ['id' => 902, 'category_id' => 18, 'product_id' => 3191, 'created_at' => null, 'updated_at' => null],
            ['id' => 903, 'category_id' => 41, 'product_id' => 3192, 'created_at' => null, 'updated_at' => null],
            ['id' => 904, 'category_id' => 18, 'product_id' => 3192, 'created_at' => null, 'updated_at' => null],
            ['id' => 905, 'category_id' => 39, 'product_id' => 3193, 'created_at' => null, 'updated_at' => null],
            ['id' => 906, 'category_id' => 18, 'product_id' => 3193, 'created_at' => null, 'updated_at' => null],
            ['id' => 907, 'category_id' => 39, 'product_id' => 3194, 'created_at' => null, 'updated_at' => null],
            ['id' => 908, 'category_id' => 18, 'product_id' => 3194, 'created_at' => null, 'updated_at' => null],
            ['id' => 909, 'category_id' => 39, 'product_id' => 3195, 'created_at' => null, 'updated_at' => null],
            ['id' => 910, 'category_id' => 18, 'product_id' => 3195, 'created_at' => null, 'updated_at' => null],
            ['id' => 911, 'category_id' => 39, 'product_id' => 3196, 'created_at' => null, 'updated_at' => null],
            ['id' => 912, 'category_id' => 18, 'product_id' => 3196, 'created_at' => null, 'updated_at' => null],
            ['id' => 913, 'category_id' => 39, 'product_id' => 3197, 'created_at' => null, 'updated_at' => null],
            ['id' => 914, 'category_id' => 18, 'product_id' => 3197, 'created_at' => null, 'updated_at' => null],
            ['id' => 915, 'category_id' => 39, 'product_id' => 3198, 'created_at' => null, 'updated_at' => null],
            ['id' => 916, 'category_id' => 18, 'product_id' => 3198, 'created_at' => null, 'updated_at' => null],
            ['id' => 917, 'category_id' => 39, 'product_id' => 3199, 'created_at' => null, 'updated_at' => null],
            ['id' => 918, 'category_id' => 18, 'product_id' => 3199, 'created_at' => null, 'updated_at' => null],
            ['id' => 919, 'category_id' => 39, 'product_id' => 3200, 'created_at' => null, 'updated_at' => null],
            ['id' => 920, 'category_id' => 18, 'product_id' => 3200, 'created_at' => null, 'updated_at' => null],
            ['id' => 921, 'category_id' => 41, 'product_id' => 3201, 'created_at' => null, 'updated_at' => null],
            ['id' => 922, 'category_id' => 18, 'product_id' => 3201, 'created_at' => null, 'updated_at' => null],
            ['id' => 923, 'category_id' => 41, 'product_id' => 3202, 'created_at' => null, 'updated_at' => null],
            ['id' => 924, 'category_id' => 18, 'product_id' => 3202, 'created_at' => null, 'updated_at' => null],
            ['id' => 925, 'category_id' => 41, 'product_id' => 3203, 'created_at' => null, 'updated_at' => null],
            ['id' => 926, 'category_id' => 18, 'product_id' => 3203, 'created_at' => null, 'updated_at' => null],
            ['id' => 927, 'category_id' => 18, 'product_id' => 3204, 'created_at' => null, 'updated_at' => null],
            ['id' => 928, 'category_id' => 43, 'product_id' => 3204, 'created_at' => null, 'updated_at' => null],
            ['id' => 929, 'category_id' => 43, 'product_id' => 3205, 'created_at' => null, 'updated_at' => null],
            ['id' => 930, 'category_id' => 18, 'product_id' => 3206, 'created_at' => null, 'updated_at' => null],
            ['id' => 931, 'category_id' => 43, 'product_id' => 3206, 'created_at' => null, 'updated_at' => null],
            ['id' => 932, 'category_id' => 44, 'product_id' => 3207, 'created_at' => null, 'updated_at' => null],
            ['id' => 933, 'category_id' => 18, 'product_id' => 3207, 'created_at' => null, 'updated_at' => null],
            ['id' => 934, 'category_id' => 44, 'product_id' => 3208, 'created_at' => null, 'updated_at' => null],
            ['id' => 935, 'category_id' => 18, 'product_id' => 3208, 'created_at' => null, 'updated_at' => null],
            ['id' => 936, 'category_id' => 44, 'product_id' => 3209, 'created_at' => null, 'updated_at' => null],
            ['id' => 937, 'category_id' => 18, 'product_id' => 3209, 'created_at' => null, 'updated_at' => null],
            ['id' => 938, 'category_id' => 44, 'product_id' => 3210, 'created_at' => null, 'updated_at' => null],
            ['id' => 939, 'category_id' => 18, 'product_id' => 3210, 'created_at' => null, 'updated_at' => null],
            ['id' => 940, 'category_id' => 44, 'product_id' => 3211, 'created_at' => null, 'updated_at' => null],
            ['id' => 941, 'category_id' => 18, 'product_id' => 3211, 'created_at' => null, 'updated_at' => null],
            ['id' => 942, 'category_id' => 44, 'product_id' => 3212, 'created_at' => null, 'updated_at' => null],
            ['id' => 943, 'category_id' => 18, 'product_id' => 3212, 'created_at' => null, 'updated_at' => null],
            ['id' => 944, 'category_id' => 44, 'product_id' => 3213, 'created_at' => null, 'updated_at' => null],
            ['id' => 945, 'category_id' => 18, 'product_id' => 3213, 'created_at' => null, 'updated_at' => null],
            ['id' => 946, 'category_id' => 45, 'product_id' => 3214, 'created_at' => null, 'updated_at' => null],
            ['id' => 947, 'category_id' => 18, 'product_id' => 3214, 'created_at' => null, 'updated_at' => null],
            ['id' => 948, 'category_id' => 45, 'product_id' => 3215, 'created_at' => null, 'updated_at' => null],
            ['id' => 949, 'category_id' => 48, 'product_id' => 3216, 'created_at' => null, 'updated_at' => null],
            ['id' => 950, 'category_id' => 18, 'product_id' => 3216, 'created_at' => null, 'updated_at' => null],
            ['id' => 951, 'category_id' => 41, 'product_id' => 3217, 'created_at' => null, 'updated_at' => null],
            ['id' => 952, 'category_id' => 18, 'product_id' => 3217, 'created_at' => null, 'updated_at' => null],
            ['id' => 953, 'category_id' => 18, 'product_id' => 3218, 'created_at' => null, 'updated_at' => null],
            ['id' => 954, 'category_id' => 18, 'product_id' => 3219, 'created_at' => null, 'updated_at' => null],
            ['id' => 955, 'category_id' => 43, 'product_id' => 3219, 'created_at' => null, 'updated_at' => null],
            ['id' => 956, 'category_id' => 48, 'product_id' => 3220, 'created_at' => null, 'updated_at' => null],
            ['id' => 957, 'category_id' => 18, 'product_id' => 3220, 'created_at' => null, 'updated_at' => null],
            ['id' => 958, 'category_id' => 18, 'product_id' => 3221, 'created_at' => null, 'updated_at' => null],
            ['id' => 959, 'category_id' => 46, 'product_id' => 3221, 'created_at' => null, 'updated_at' => null],
            ['id' => 960, 'category_id' => 18, 'product_id' => 3222, 'created_at' => null, 'updated_at' => null],
            ['id' => 961, 'category_id' => 46, 'product_id' => 3222, 'created_at' => null, 'updated_at' => null],
            ['id' => 962, 'category_id' => 18, 'product_id' => 3223, 'created_at' => null, 'updated_at' => null],
            ['id' => 963, 'category_id' => 50, 'product_id' => 3224, 'created_at' => null, 'updated_at' => null],
            ['id' => 964, 'category_id' => 18, 'product_id' => 3224, 'created_at' => null, 'updated_at' => null],
            ['id' => 965, 'category_id' => 50, 'product_id' => 3225, 'created_at' => null, 'updated_at' => null],
            ['id' => 966, 'category_id' => 18, 'product_id' => 3225, 'created_at' => null, 'updated_at' => null],
            ['id' => 967, 'category_id' => 50, 'product_id' => 3226, 'created_at' => null, 'updated_at' => null],
            ['id' => 968, 'category_id' => 18, 'product_id' => 3226, 'created_at' => null, 'updated_at' => null],
            ['id' => 969, 'category_id' => 50, 'product_id' => 3227, 'created_at' => null, 'updated_at' => null],
            ['id' => 970, 'category_id' => 18, 'product_id' => 3227, 'created_at' => null, 'updated_at' => null],
            ['id' => 971, 'category_id' => 18, 'product_id' => 3228, 'created_at' => null, 'updated_at' => null],
            ['id' => 972, 'category_id' => 18, 'product_id' => 3229, 'created_at' => null, 'updated_at' => null],
            ['id' => 973, 'category_id' => 12, 'product_id' => 3230, 'created_at' => null, 'updated_at' => null],
            ['id' => 974, 'category_id' => 64, 'product_id' => 3231, 'created_at' => null, 'updated_at' => null],
            ['id' => 975, 'category_id' => 66, 'product_id' => 3232, 'created_at' => null, 'updated_at' => null],
            ['id' => 976, 'category_id' => 12, 'product_id' => 3232, 'created_at' => null, 'updated_at' => null],
            ['id' => 977, 'category_id' => 12, 'product_id' => 3231, 'created_at' => null, 'updated_at' => null],
            ['id' => 978, 'category_id' => 12, 'product_id' => 3233, 'created_at' => null, 'updated_at' => null],
            ['id' => 979, 'category_id' => 12, 'product_id' => 3234, 'created_at' => null, 'updated_at' => null],
            ['id' => 980, 'category_id' => 49, 'product_id' => 3235, 'created_at' => null, 'updated_at' => null],
            ['id' => 981, 'category_id' => 18, 'product_id' => 3235, 'created_at' => null, 'updated_at' => null],
            ['id' => 982, 'category_id' => 49, 'product_id' => 3236, 'created_at' => null, 'updated_at' => null],
            ['id' => 983, 'category_id' => 18, 'product_id' => 3236, 'created_at' => null, 'updated_at' => null],
            ['id' => 984, 'category_id' => 49, 'product_id' => 3237, 'created_at' => null, 'updated_at' => null],
            ['id' => 985, 'category_id' => 18, 'product_id' => 3237, 'created_at' => null, 'updated_at' => null],
            ['id' => 986, 'category_id' => 18, 'product_id' => 3238, 'created_at' => null, 'updated_at' => null],
            ['id' => 987, 'category_id' => 18, 'product_id' => 3239, 'created_at' => null, 'updated_at' => null],
            ['id' => 988, 'category_id' => 18, 'product_id' => 3240, 'created_at' => null, 'updated_at' => null],
            ['id' => 989, 'category_id' => 13, 'product_id' => 3241, 'created_at' => null, 'updated_at' => null],
            ['id' => 990, 'category_id' => 13, 'product_id' => 3242, 'created_at' => null, 'updated_at' => null],
            ['id' => 991, 'category_id' => 62, 'product_id' => 3243, 'created_at' => null, 'updated_at' => null],
            ['id' => 992, 'category_id' => 62, 'product_id' => 3244, 'created_at' => null, 'updated_at' => null],
            ['id' => 993, 'category_id' => 62, 'product_id' => 3245, 'created_at' => null, 'updated_at' => null],
            ['id' => 994, 'category_id' => 11, 'product_id' => 3243, 'created_at' => null, 'updated_at' => null],
            ['id' => 995, 'category_id' => 11, 'product_id' => 3245, 'created_at' => null, 'updated_at' => null],
            ['id' => 996, 'category_id' => 11, 'product_id' => 3244, 'created_at' => null, 'updated_at' => null],
            ['id' => 997, 'category_id' => 11, 'product_id' => 3246, 'created_at' => null, 'updated_at' => null],
            ['id' => 998, 'category_id' => 62, 'product_id' => 3246, 'created_at' => null, 'updated_at' => null],
            ['id' => 999, 'category_id' => 11, 'product_id' => 3247, 'created_at' => null, 'updated_at' => null],
            ['id' => 1000, 'category_id' => 62, 'product_id' => 3247, 'created_at' => null, 'updated_at' => null],
            ['id' => 1001, 'category_id' => 61, 'product_id' => 3248, 'created_at' => null, 'updated_at' => null],
            ['id' => 1002, 'category_id' => 11, 'product_id' => 3248, 'created_at' => null, 'updated_at' => null],
            ['id' => 1003, 'category_id' => 61, 'product_id' => 3249, 'created_at' => null, 'updated_at' => null],
            ['id' => 1004, 'category_id' => 11, 'product_id' => 3249, 'created_at' => null, 'updated_at' => null],
            ['id' => 1005, 'category_id' => 61, 'product_id' => 3250, 'created_at' => null, 'updated_at' => null],
            ['id' => 1006, 'category_id' => 11, 'product_id' => 3250, 'created_at' => null, 'updated_at' => null],
            ['id' => 1007, 'category_id' => 61, 'product_id' => 3251, 'created_at' => null, 'updated_at' => null],
            ['id' => 1008, 'category_id' => 11, 'product_id' => 3251, 'created_at' => null, 'updated_at' => null],
            ['id' => 1009, 'category_id' => 61, 'product_id' => 3252, 'created_at' => null, 'updated_at' => null],
            ['id' => 1010, 'category_id' => 11, 'product_id' => 3252, 'created_at' => null, 'updated_at' => null],
        ]);
    }
}
